# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-14 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('altura', models.IntegerField()),
                ('localidad', models.IntegerField()),
                ('provincia', models.IntegerField(default=1)),
                ('instalacion', models.DateField()),
            ],
        ),
    ]
